#!/usr/bin/env python

import sys
import os.path

try:
    import cxxtest.cxxtestgen
except ImportError:
    currdir = os.path.dirname(os.path.abspath(__file__))
    pydir = os.path.dirname(currdir)
    if sys.version_info[0] >= 3:
        pydir = os.path.join(pydir, 'python3')
    sys.path.append(pydir)
    import cxxtest.cxxtestgen

cxxtest.cxxtestgen.main()
