#!/bin/bash

export PATH=$WORKSPACE/python/bin:$PATH
g++ --version

# Setup Python environment
\rm -Rf python
vpy/scripts/vpy_install
python/bin/easy_install nose
python/bin/easy_install unittest2
python/bin/easy_install ply
python/bin/easy_install ordereddict
python/bin/easy_install gcovr
python/bin/easy_install pyutilib.th
cd cxxtest/python
../../python/bin/python setup.py install

# Cleanup test directory
cd ../test
make clean
cd ../..

# Run tests
export CXXTEST_GCOV_FLAGS='-fprofile-arcs -ftest-coverage'
python/bin/nosetests -v -v --with-xunit --xunit-file=$WORKSPACE/TEST-cxxtest.xml -w $WORKSPACE/cxxtest/test

# Generate code coverage
cd cxxtest
../python/bin/gcovr -v -r $WORKSPACE/cxxtest -x -o $WORKSPACE/cxxtest/test/coverage.xml --gcov-filter '.*#test#(\.\.|^)#cxxtest#.*gcov'

echo "DONE"

# Cleanup old gcov files
##cd $WORKSPACE
##\rm -f *.gcov cxxtest/*.gcov doc/*.gcov doc/examples/*.gcov
##\rm -f *.gcno cxxtest/*.gcno doc/*.gcno doc/examples/*.gcno
##\rm -f *.gcda cxxtest/*.gcda doc/*.gcda doc/examples/*.gcda
##cd $WORKSPACE/cxxtest/test
##make clean

