#!/bin/bash

if test -z "$WORKSPACE"; then
    echo "ERROR: \$WORKSPACE not defined"
    exit 1
fi

export PATH="$WORKSPACE/vpython/bin:$PATH"
g++ --version

# Setup virtual Python environment
\rm -Rf vpython
python cxxtest/admin/virtualenv.py vpython
#vpy/scripts/vpy_install
vpython/bin/easy_install nose
vpython/bin/easy_install unittest2
vpython/bin/easy_install ply
vpython/bin/easy_install ordereddict
vpython/bin/easy_install gcovr
vpython/bin/easy_install pyutilib.th
cd "$WORKSPACE"/cxxtest/python
"$WORKSPACE"/vpython/bin/python setup.py install

# Cleanup test directory
cd "$WORKSPACE"/cxxtest/test
make clean
cd "$WORKSPACE"

# Run tests
export CXXTEST_GCOV_FLAGS='-fprofile-arcs -ftest-coverage'
vpython/bin/nosetests -v -v -w "$WORKSPACE"/cxxtest/test \
    --with-xunit --xunit-file="$WORKSPACE"/TEST-cxxtest.xml \
    || echo "(INFO) nosetests returned non-zero return code"

# Generate code coverage
cd "$WORKSPACE"/cxxtest
"$WORKSPACE"/vpython/bin/gcovr -v -d -r "$WORKSPACE"/cxxtest \
    -x -o "$WORKSPACE"/cxxtest/test/coverage.xml \
    --gcov-filter '.*#test#(\.\.|\^)#cxxtest#.*gcov'

echo "DONE"

# Cleanup old test files
cd $WORKSPACE/cxxtest/test
make clean

